### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by jeroenooms** [r-pkgs/roxygen2md#1]
If the `DESCRIPTION` file does not contain `Roxygen: list(markdown = TRUE)` we get a cryptic error:

```
> roxygen2md::roxygen2md()
Error in roxygen_field_val$markdown : 
  $ operator is invalid for atomic vectors
```

Took me a while to debug this, better error message would be nice.

**Comment by krlmlr** [comment]
Sorry for that. That's what we get when we don't have tests in the code...
